services:
  - type: web
    name: calong-pos-system
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: DATA_DIR
        value: ./data
      - key: POS_USER
        sync: false
      - key: POS_PASSWORD
        sync: false
