services:
  - type: web
    name: calong-pos-system
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: DATA_DIR
        value: ./data
      - key: POS_USER
        sync: false
      - key: POS_PASSWORD
        sync: false
      - key: GDRIVE_SERVICE_ACCOUNT
        sync: false
      - key: GDRIVE_FOLDER_ID
        sync: false
      - key: GDRIVE_WEBAPP_URL
        sync: false
      - key: GDRIVE_WEBAPP_SECRET
        sync: false
